name: Build

on: [push]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        build_configuration: [Debug, Release]
    env:
        BUILD_CONFIGURATION: ${{ matrix.build_configuration }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Add NuGet source
      working-directory: ${{env.GITHUB_WORKSPACE}}
      env:
        UCP3_READ_PACKAGES: ${{ secrets.UCP3_READ_PACKAGES }}
      run: nuget sources add -Name "gynt-packages" -Source "https://nuget.pkg.github.com/gynt/index.json" -StorePasswordInClearText -Username git -Password "$env:UCP3_READ_PACKAGES"

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore

    - name: Build UCP3
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
      
    - name: Prepare UCP3 package
      shell: pwsh
      run: |
        # Create the right folders
        mkdir "$env:BUILD_CONFIGURATION\ucp-package"
        mkdir "$env:BUILD_CONFIGURATION\ucp-package\ucp"
        
        # Copy the dll files, rename dll.dll to binkw32_ucp.dll
        $dllfiles = Get-ChildItem $env:BUILD_CONFIGURATION\*.dll
        Copy-Item $dllfiles -Destination "$env:BUILD_CONFIGURATION\ucp-package\" -Recurse
        Rename-Item -Path "$env:BUILD_CONFIGURATION\ucp-package\dll.dll" -NewName "binkw32_ucp.dll"
        
        # Copy the bat file that renames binkw32_ucp.dll to binkw32.dll and backs up binkw32.dll to binkw32_real.dll (if necessary)
        Copy-Item installer\rename-dlls.bat "$env:BUILD_CONFIGURATION\ucp-package\install.bat"
        
        # Copy all content/ucp files ucp-package/ucp, except the modules folder
        $mainfiles = Get-ChildItem content\ucp | Where({$_.Name -ne "modules"})  | foreach{$_.FullName}
        Copy-Item $mainfiles -Destination "$env:BUILD_CONFIGURATION\ucp-package\ucp" -Recurse
        
        # Copy the legacy ucp.cfg
        Copy-Item installer\ucp.cfg "$env:BUILD_CONFIGURATION\ucp-package\ucp.cfg"
        
        ### Build each module if required, and then package the module by copying the right files
        # List of modules
        $modules = Get-ChildItem -Directory content\ucp\modules
        foreach($module in $modules) {
          
          # Create the module directory in the ucp-package\ucp\modules folder
          New-Item -Path "$env:BUILD_CONFIGURATION\ucp-package\ucp\modules\" -Name $module.Name -ItemType "directory"
          $moduleDir = "$env:BUILD_CONFIGURATION\ucp-package\ucp\modules\" + $module.Name + "\"
          
          # If the module uses C++ we have to build it first
          $hasVCXProj = Test-Path -Path ($module.FullName + "\*.vcxproj")
          
          # If the module specifies a custom list of files to include, read that
          $hasFilesList = Test-Path -Path ($module.FullName + "\module.files")
          
          # Build the module
          if($hasVCXProj) {
            pushd $module.FullName
            nuget restore
            msbuild /m /p:Configuration=$env:BUILD_CONFIGURATION
            popd
          }
          
          # Copy the specified files, or *.lua and module.yml if no module.files file was found.
          if($hasFilesList) {
            $node = Select-Xml -XPath "/module/files" -Path ($module.FullName + "\module.files")
            $moduleFiles = $node.Node.file
            foreach($moduleFile in $moduleFiles) {
              # To allow specification of $(Configuration) in "src" in module.files, we substitute it with the right value here
              $srcFile = $moduleFile.src.Replace("`$(Configuration)", "$env:BUILD_CONFIGURATION")
              
              # Copy the file, can include wildcards
              Copy-Item ($module.FullName + "\" + $srcFile) -Destination $moduleDir -Recurse
            }
          } else {
            # TODO: avoid this wildcard. Include .lua .yml and ... only?
            Copy-Item ($module.FullName + "\*") -Destination $moduleDir -Recurse
          }
        }
    - name: Generate a default config
      shell: pwsh
      run: |
        Install-Module powershell-yaml -Scope CurrentUser -Force
        Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
        Import-Module powershell-yaml
        
        # Function to convert a options.yml definition to a simplified ucp-config.yml style format
        function Convert-ConfigFile {
            param (
                [hashtable]$Table
            )
            if($Table.ContainsKey("default")) {
                # We reached a terminal node
                return $Table.default
            } else 
            {
                # We did not reach a terminal node, continue looking for terminals, collect them
                $nht = [ordered]@{}
                foreach($key in $Table.keys) {
                    if($Table[$key] -is [System.Collections.IDictionary]) {
                        # This might be a good terminal node candidate.
                        $nht[$key] = Convert-ConfigFile -Table $Table[$key]
                    } else 
                    {
                        $nht[$key] = $Table[$key]
                    }
                }
                return $nht
            }
        }
        
        $defaults = [ordered]@{"modules"=[ordered]@{}}
        
        $modules = Get-ChildItem -Directory content\ucp\modules
        
        foreach($module in $modules) {
            $i = Get-Content -Path ($module.FullName + "\module.yml") -Raw
            $iy = ConvertFrom-Yaml $i
            
            $name = $iy.name
            $version = $iy.version
            
            $defaults.modules[$name] = [ordered]@{}
            $defaults.modules[$name].active = $true
            $defaults.modules[$name].version = $version
            
            if(Test-Path -Path ($module.FullName + "\options.yml")) {
                $defaults.modules[$name].options = [ordered]@{}
                
                $f = Get-Content -Path ($module.FullName + "\options.yml") -Raw
                $y = ConvertFrom-Yaml $f
                $defaults.modules[$name].options = Convert-ConfigFile -Table $y                
            }
        }
        
        $o = ConvertTo-Yaml $defaults
        Set-Content -Path "$env:BUILD_CONFIGURATION\ucp-package\ucp-config-defaults.yml" -Value $o
    - name: Generate a snapshot UCP3 artifact name
      shell: pwsh
      run: |
        $name = "$env:GITHUB_SHA".SubString(0, 10)
        $type = "$env:BUILD_CONFIGURATION" #.SubString(0, 1)
        echo "NAME=UCP3-snapshot-$type-$name" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
    - name: Upload UCP3 as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.NAME }}
        path: ${{ env.BUILD_CONFIGURATION }}/ucp-package/*
