name: Build

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
      - feature-testing
  pull_request:
    branches:
      - main
      - feature-testing
  # Also trigger on page_build, as well as release created events
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .
  VERSION_MAJOR: 3
  VERSION_MINOR: 0
  VERSION_PATCH: 0

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        build_configuration: [Debug, Release, DebugSecure, ReleaseSecure]
    env:
        BUILD_CONFIGURATION: ${{ matrix.build_configuration }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Run build script
      working-directory: ${{env.GITHUB_WORKSPACE}}
      env:
        UCP3_READ_PACKAGES: ${{ secrets.UCP3_READ_PACKAGES }}
      shell: pwsh
      run: |
        .\scripts\build.ps1 -Build "$env:BUILD_CONFIGURATION" -NugetToken "$env:UCP3_READ_PACKAGES"


    - name: Prepare signing by exporting secret to file
      shell: pwsh
      working-directory: ${{env.GITHUB_WORKSPACE}}
      env:
        UCP3_SIGNING_CERTIFICATE_CONTENTS: ${{ secrets.UCP3_SIGNING_CERTIFICATE_CONTENTS }}
      run: |
        Set-Content -Value "$UCP3_SIGNING_CERTIFICATE_CONTENTS" -Path "ucp3-module-signing-key.pem" -Force

    - name: Zip and sign extensions
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: pwsh
      run: |
        .\scripts\signer.ps1 -Path "$($env:BUILD_CONFIGURATION)\ucp-package\ucp\ -RemoveZippedFolders -Certificate ucp3-module-signing-key.pem 

    - name: Generate a snapshot UCP3 artifact name
      shell: pwsh
      run: |
        $name = "$env:GITHUB_SHA".SubString(0, 10)
        $type = "$env:BUILD_CONFIGURATION" #.SubString(0, 1)
        if($env:BUILD_CONFIGURATION -eq "Debug") {
          $type = "DevDebug"
        }
        if($env:BUILD_CONFIGURATION -eq "DebugSecure") {
          $type = "Debug"
        }
        if($env:BUILD_CONFIGURATION -eq "Release") {
          $type = "DevRelease"
        }
        if($env:BUILD_CONFIGURATION -eq "ReleaseSecure") {
          $type = "Release"
        }
        $env:NAME = "UCP3-snapshot-$type-$name"
        echo "NAME=UCP3-snapshot-$type-$name" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
    
    - name: Upload UCP3 as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.NAME }}
        path: ${{ env.BUILD_CONFIGURATION }}/ucp-package/*
        retention-days: 1

  release:
    if: github.event_name == 'workflow_dispatch'
    needs: build
    runs-on: windows-latest
    steps:
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts
      
    - name: zip artifacts
      shell: pwsh
      run: |
        pushd artifacts
        
        $artifactDirs = Get-ChildItem -Directory
        foreach($artifactDir in $artifactDirs) {
          $dirName = $artifactDir.name
          pushd $artifactDir
          7z a -tzip -m0=Copy "..\$dirName.zip" *
          popd
        }
        
        popd
      
      
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "artifacts/*.zip"
        token: "${{ secrets.GITHUB_TOKEN }}"      
        tag: "latest"
        commit: "main"
        allowUpdates: true
        name: "Development Build"
        prerelease: true
        replacesArtifacts: true
        removeArtifacts: true
         
